permissions:
  id-token: write # Это необходимо для запроса JWT
  contents: read  # Это необходимо для actions/checkout

on: 
  #push:
  #  branches: [ main ]
  # Позволяет запускать этот workflow вручную из вкладки Actions
  workflow_dispatch:

env:
  FUNCTION_ID: d4e4r8q8kjlh7711a2d3
  FUNCTION_RUNTIME: nodejs22
  FUNCTION_ENTRYPOINT: index.handler
  FUNCTION_MEMORY: 134217728
  FUNCTION_SOURCEROOT: .
  SA_ID: ajejocsfa1jj33b9g8sk
  
jobs:
  function_version_deployment_job:
    runs-on: ubuntu-latest
    name: Function redeployment job
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      # Упаковать все в zip
      - name: Zip the code
        run: |
          zip function.zip ./*.js ./*.json
      - name: Install dependencies
        run: npm ci
      - run: npm run build --if-present
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core @actions/http-client
      # Получение рабочего токена workflow
      - name: Get Id Token
        uses: actions/github-script@v7
        id: tokenid
        with:
          script: |
            const coredemo = require('@actions/core')
            let id_token = await coredemo.getIDToken()
            coredemo.setOutput('id_token', id_token)
            console.log(context)
            
      # Обмен рабочего токена workflow на IAM-токен сервисного аккаунта в Yandex Cloud
      - name: GetIAMToken
        run: |
          
          IAMTOKEN=$(curl -sH "Content-Type: application/x-www-form-urlencoded" -d "grant_type=urn:ietf:params:oauth:grant-type:token-exchange&requested_token_type=urn:ietf:params:oauth:token-type:access_token&audience=${{env.SA_ID}}&subject_token=${{steps.tokenid.outputs.id_token}}&subject_token_type=urn:ietf:params:oauth:token-type:id_token" -X POST https://auth.yandex.cloud/oauth/token | jq -r '.access_token')
          echo "IAMToken=${IAMTOKEN}" >> $GITHUB_OUTPUT
        id: IAMtoken

      # Запрос списка функций через API с использованием IAM токена в Yandex Cloud
      - name: Trigger function redeployment step
        id: redeployment
        run: |
          FILE_BYTES=$(cat ./function.zip | base64)
                      
          RESPONSE=$(curl -X POST -sH "Authorization: Bearer ${{steps.IAMtoken.outputs.IAMTOKEN}}" https://serverless-functions.api.cloud.yandex.net/functions/v1/versions \
            -d @- << EOF 
          { 
            "functionId": "${{env.FUNCTION_ID}}",
            "runtime": "${{env.FUNCTION_RUNTIME}}",
            "entrypoint": "${{env.FUNCTION_ENTRYPOINT}}", 
            "resources": { 
              "memory": "${{env.FUNCTION_MEMORY}}"
            },
            "executionTimeout": "3s", 
            "content": '${FILE_BYTES}'
          }
          EOF
          )
          echo "----- Яндекс Клауд Функшн API ответ -----"
          echo "$RESPONSE"
